In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
#data frame and read from csv file
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [1]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

NameError: name 'df' is not defined

In [7]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
reg = linear_model.LinearRegression()
#h fit xrhsimopoieitai gia na ekapideusei to montelo me ena training set
#auto ginetai me ena df emfoleumeno sthn fit
#here the data frame used for training has 3 independant variables and price as a traget variable
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [9]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [10]:
reg.intercept_

221323.00186540425

In [11]:
#predicting a house with 3000 sqr feet ,3 bedrooms and 40 years old
reg.predict([[3000,3,40]])
#afou ektelestei mporw na kanw enan elegxo manually 

array([498408.25158031])

In [12]:
reg.predict([[2500,4,5]])

array([578876.03748933])